Repository Nexters/water-android, pull requests merged in 2020-08, with the labels that each got.

#18 Hot fix/db
  app/build.gradle
  app/src/main/java/appvian/water/buddy/model/datasource/local/WaterBuddyDb.kt
  app/src/main/java/appvian/water/buddy/model/datasource/local/intakeDao.kt
  app/src/main/java/appvian/water/buddy/model/repository/HomeRepository.kt
  app/src/main/java/appvian/water/buddy/view/MainFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/viewmodel/HomeViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/MainViewModel.kt
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/layout/fragment_daily_chart.xml
  app/src/main/res/layout/fragment_weekly_chart.xml
  app/src/main/res/mipmap-hdpi/no_water_grey_icon.png
  app/src/main/res/mipmap-mdpi/no_water_grey_icon.png
  app/src/main/res/mipmap-xhdpi/no_water_grey_icon.png
  app/src/main/res/mipmap-xxhdpi/no_water_grey_icon.png
  app/src/main/res/mipmap-xxxhdpi/no_water_grey_icon.png
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: hot fix

#10 Feature/analytics total page
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: new feature, review needed

#24 Feature/profile edit
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/appvian/water/buddy/model/data/SharedPreferenceLiveData.kt
  app/src/main/java/appvian/water/buddy/model/repository/SharedPrefsRepository.java
  app/src/main/java/appvian/water/buddy/view/settings/AlarmSettingActivity.kt
  app/src/main/java/appvian/water/buddy/view/settings/FavoriteDrinkSettingActivity.kt
  app/src/main/java/appvian/water/buddy/view/settings/PopupActivity.kt
  app/src/main/java/appvian/water/buddy/view/settings/ProfileEditActivity.kt
  app/src/main/java/appvian/water/buddy/view/settings/SettingFragment.kt
  app/src/main/java/appvian/water/buddy/view/settings/TargetAmountSettingActivity.kt
  app/src/main/java/appvian/water/buddy/viewmodel/MainViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/SettingViewModel.kt
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/arrow_right.png
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/setting_card_back.xml
  app/src/main/res/drawable/setting_popup_back.xml
  app/src/main/res/drawable/setting_save_btn.xml
  app/src/main/res/drawable/setting_save_btn_inactive.xml
  app/src/main/res/layout/activity_alarm_setting.xml
  app/src/main/res/layout/activity_favorite_drink_setting.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_target_amount_setting.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/popup_setting.xml
  app/src/main/res/layout/tmp.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: new feature

#30 Feature/chart daily
  app/src/main/java/appvian/water/buddy/model/datasource/local/intakeDao.kt
  app/src/main/java/appvian/water/buddy/util/DrinkMapper.kt
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyAdapter.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyLegendAdapter.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/DailyChartViewModel.kt
  app/src/main/res/drawable/ic_drink_1.xml
  app/src/main/res/drawable/ic_drink_2.xml
  app/src/main/res/drawable/ic_drink_3.xml
  app/src/main/res/drawable/ic_drink_4.xml
  app/src/main/res/drawable/ic_drink_5.xml
  app/src/main/res/drawable/ic_drink_6.xml
  app/src/main/res/drawable/ic_drink_7.xml
  app/src/main/res/drawable/ic_drink_8.xml
  app/src/main/res/drawable/ic_drink_9.xml
  app/src/main/res/drawable/picker_background.xml
  app/src/main/res/layout/daily_date_picker.xml
  app/src/main/res/layout/fragment_daily_chart.xml
  app/src/main/res/layout/item_daily_intake_list.xml
  app/src/main/res/layout/item_daily_legend.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: new feature, review needed

#35 Feature/weekly chart
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/java/appvian/water/buddy/model/datasource/local/intakeDao.kt
  app/src/main/java/appvian/water/buddy/model/repository/HomeRepository.kt
  app/src/main/java/appvian/water/buddy/util/DrinkMapper.kt
  app/src/main/java/appvian/water/buddy/util/TimeUtil.kt
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyValueFormatter.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/DailyChartViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/WeeklyViewModel.kt
  app/src/main/res/drawable/ic_quotation_mark_back.xml
  app/src/main/res/drawable/ic_quotation_mark_front.xml
  app/src/main/res/drawable/picker_background.xml
  app/src/main/res/layout/daily_date_picker.xml
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/layout/fragment_weekly_chart.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: new feature, review needed

#47 Hotfix/daily legend
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyLegendAdapter.kt
  app/src/main/res/layout/fragment_daily_chart.xml
  app/src/main/res/values/dimens.xml
Labels: hot fix

#57 Feature/month picker
  app/src/main/java/appvian/water/buddy/util/TimeUtil.kt
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/month/CharacterAdapter.kt
  app/src/main/java/appvian/water/buddy/view/analytics/month/MonthFragment.kt
  app/src/main/java/appvian/water/buddy/view/modal/MonthCallbackListener.kt
  app/src/main/java/appvian/water/buddy/view/modal/MonthModal.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/MonthViewModel.kt
  app/src/main/res/drawable/ic_full.xml
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/layout/fragment_month_chart.xml
  app/src/main/res/layout/month_picker.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: new feature

#62 Cal picker
  app/src/main/java/appvian/water/buddy/model/data/CalendarData.kt
  app/src/main/java/appvian/water/buddy/util/TimeUtil.kt
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarAdapter.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarDayListener.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarModal.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarTotalListener.kt
  app/src/main/java/appvian/water/buddy/view/modal/month/MonthCallbackListener.kt
  app/src/main/java/appvian/water/buddy/view/modal/month/MonthModal.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/DailyChartViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/modal/CalendarViewModel.kt
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/drawable/arrow_right.png
  app/src/main/res/drawable/arrow_right.xml
  app/src/main/res/drawable/circle.xml
  app/src/main/res/layout/calendar_legend.xml
  app/src/main/res/layout/calendar_picker.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_daily_chart.xml
  app/src/main/res/layout/fragment_weekly_chart.xml
  app/src/main/res/layout/wb_calendar_item.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#65 Feature/modify analytics
  app/src/main/java/appvian/water/buddy/view/analytics/AnalyticsFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/daily/DailyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/month/MonthFragment.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarModal.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/AnalyticsViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/modal/CalendarViewModel.kt
Labels: enhancement

#70 Hotfix/main fragment bug
  .idea/gradle.xml
  app/src/main/java/appvian/water/buddy/view/home/MainFragment.kt
  app/src/main/res/layout/activity_daily_intake_list.xml
Labels: hot fix

#72 통계와 sharedPreference 데이터 연결
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/month/MonthFragment.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/MonthViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/WeeklyViewModel.kt
Labels: enhancement

#80 Feature/tutorial
  app/src/main/AndroidManifest.xml
  app/src/main/java/appvian/water/buddy/view/Intro/IntroFourthFragment.kt
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialActivity.kt
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialViewPagerAdapter.kt
  app/src/main/java/appvian/water/buddy/view/Intro/onBoardingTutorial.kt
  app/src/main/res/drawable-hdpi/button_close.png
  app/src/main/res/drawable-hdpi/tutorial_1.png
  app/src/main/res/drawable-hdpi/tutorial_2.png
  app/src/main/res/drawable-mdpi/button_close.png
  app/src/main/res/drawable-mdpi/tutorial_1.png
  app/src/main/res/drawable-mdpi/tutorial_2.png
  app/src/main/res/drawable-xhdpi/button_close.png
  app/src/main/res/drawable-xhdpi/tutorial_1.png
  app/src/main/res/drawable-xhdpi/tutorial_2.png
  app/src/main/res/drawable-xxhdpi/button_close.png
  app/src/main/res/drawable-xxhdpi/tutorial_1.png
  app/src/main/res/drawable-xxhdpi/tutorial_2.png
  app/src/main/res/drawable-xxxhdpi/button_close.png
  app/src/main/res/drawable-xxxhdpi/tutorial_1.png
  app/src/main/res/drawable-xxxhdpi/tutorial_2.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_tutorial_on_boarding.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review needed

#78 Hotfix/analytics
  app/src/main/java/appvian/water/buddy/util/TimeUtil.kt
  app/src/main/java/appvian/water/buddy/view/analytics/chart/weekly/WeeklyChartFragment.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarAdapter.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/WeeklyViewModel.kt
  app/src/main/res/layout/fragment_month_chart.xml
  app/src/main/res/layout/fragment_weekly_chart.xml
Labels: hot fix

#97 status bar 색상 변경
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: review needed

#98 intro edittext색과 inputType 변경
  app/src/main/res/layout/intro_second_fragment.xml
  app/src/main/res/layout/intro_third_fragment.xml
Labels: review needed

#99 뒤로 가기 누를 때 변경
  app/src/main/java/appvian/water/buddy/view/Intro/IntroFourthFragment.kt
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialActivity.kt
Labels: hot fix, review needed

#101 위젯 소수점 삭제
  app/src/main/java/appvian/water/buddy/widget/HomeWidget.kt
Labels: hot fix, review needed

#124 라인 추가
  app/src/main/res/layout/daily_intake_recyclerview_item.xml
Labels: hot fix, review needed

#126 버튼 굵기와 화살표 추가
  app/src/main/res/drawable/intake_list_button_radius.xml
  app/src/main/res/drawable/main_arrow_icon.xml
  app/src/main/res/layout/fragment_main.xml
Labels: hot fix, review needed

#127 홈 텍스트뷰 하나로 통합
  app/src/main/java/appvian/water/buddy/view/home/MainFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/strings.xml
Labels: hot fix, review needed

#128 스낵바 아련 삭제
  app/src/main/res/values/strings.xml
Labels: hot fix, review needed

#129 navigation bar 텍스트 사이즈 수정
  app/src/main/res/values/dimens.xml
Labels: hot fix, review needed

#131 오늘 마신 음료에 back button 추가
  app/src/main/java/appvian/water/buddy/view/home/DailyIntakeListActivity.kt
  app/src/main/res/layout/activity_daily_intake_list.xml
Labels: review needed

#134 Tutorial 수정
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialActivity.kt
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialFragment1.kt
  app/src/main/java/appvian/water/buddy/view/Intro/TutorialFragment2.kt
  app/src/main/java/appvian/water/buddy/view/Intro/onBoardingTutorial.kt
  app/src/main/res/drawable/tutorial_setting.xml
  app/src/main/res/layout/fragment_tutorial1.xml
  app/src/main/res/layout/fragment_tutorial2.xml
  app/src/main/res/layout/fragment_tutorial_on_boarding.xml
  app/src/main/res/mipmap-hdpi/tutorial_1.png
  app/src/main/res/mipmap-hdpi/tutorial_2.png
  app/src/main/res/mipmap-mdpi/tutorial_1.png
  app/src/main/res/mipmap-mdpi/tutorial_2.png
  app/src/main/res/mipmap-xhdpi/tutorial_1.png
  app/src/main/res/mipmap-xhdpi/tutorial_2.png
  app/src/main/res/mipmap-xxhdpi/tutorial_1.png
  app/src/main/res/mipmap-xxhdpi/tutorial_2.png
  app/src/main/res/mipmap-xxxhdpi/tutorial_1.png
  app/src/main/res/mipmap-xxxhdpi/tutorial_2.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: hot fix, review needed

#140 작은 화면에서 월간,주간,일간 제대로 표시 안되는 것 변경
  app/src/main/res/layout/fragment_analytics.xml
Labels: hot fix

#139 adaptive icon 생성 및 google_play_store_icon.png 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/appvian/water/buddy/utilities/AlarmReceiver.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/google_play_store_icon.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/google_play_store_icon.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/google_play_store_icon.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/google_play_store_icon.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/google_play_store_icon.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: hot fix

#159 Hotfix/statics header
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: hot fix

#142 Hotfix/home fragment final
  app/src/main/java/appvian/water/buddy/model/repository/HomeRepository.kt
  app/src/main/java/appvian/water/buddy/view/MainActivity.kt
  app/src/main/java/appvian/water/buddy/view/SetIntakeModal.kt
  app/src/main/java/appvian/water/buddy/view/home/DailyIntakeListActivity.kt
  app/src/main/java/appvian/water/buddy/view/home/MainFragment.kt
  app/src/main/java/appvian/water/buddy/viewmodel/HomeViewModel.kt
  app/src/main/java/appvian/water/buddy/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/back_button.xml
  app/src/main/res/layout/activity_daily_intake_list.xml
  app/src/main/res/layout/activity_favorite_drink_setting.xml
  app/src/main/res/layout/bottom_sheet_modal.xml
  app/src/main/res/layout/daily_intake_recyclerview_item.xml
  app/src/main/res/layout/fragment_main.xml
Labels: hot fix, review needed

#160 Hotfix/statics month
  app/src/main/java/appvian/water/buddy/view/analytics/month/MonthFragment.kt
  app/src/main/java/appvian/water/buddy/view/analytics/month/RankAdapter.kt
  app/src/main/java/appvian/water/buddy/viewmodel/analytics/MonthViewModel.kt
  app/src/main/res/drawable/load_more.xml
  app/src/main/res/drawable/month_wabi_background.xml
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/layout/fragment_month_chart.xml
  app/src/main/res/layout/month_character_list.xml
  app/src/main/res/values/strings.xml
Labels: hot fix

#167 onboarding text image 분리 완료
  app/src/main/java/appvian/water/buddy/view/Intro/IntroFragment.kt
  app/src/main/java/appvian/water/buddy/view/Intro/onBoardingFragment.kt
  app/src/main/res/drawable/onboarding_1.png
  app/src/main/res/drawable/onboarding_2.png
  app/src/main/res/drawable/onboarding_3.png
  app/src/main/res/layout/fragment_on_boarding.xml
Labels: hot fix

#165 Hotfix/statics modal etc
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarAdapter.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarItemDecoration.kt
  app/src/main/java/appvian/water/buddy/view/modal/calendar/CalendarModal.kt
  app/src/main/java/appvian/water/buddy/viewmodel/modal/CalendarViewModel.kt
  app/src/main/res/layout/calendar_legend.xml
  app/src/main/res/layout/calendar_picker.xml
  app/src/main/res/layout/fragment_analytics.xml
  app/src/main/res/layout/fragment_daily_chart.xml
  app/src/main/res/layout/fragment_weekly_chart.xml
  app/src/main/res/layout/month_picker.xml
  app/src/main/res/layout/wb_calendar_item.xml
Labels: hot fix
